name: Build Windows

#on:
#  create:
#    tags:
#      - '*'
on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yarn and requirements
        run: |
          $ErrorActionPreference = "Stop"
          SET GH_TOKEN= ${{ secrets.GITHUB_TOKEN }}
          if (Test-Path -Path "C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\pc-cloud") {
            Remove-Item -Path "C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\pc-cloud" -Recurse -Force
            Write-Host "Folder deleted"
          } else {
            Write-Host "Folder does not exist. Skipping deletion."
          }
          cd C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\
          git clone https://github.com/internxt/pc-cloud.git
          cd pc-cloud
          Copy-Item -Path "..\variables\.env" -Destination ".\"
          Copy-Item -Path "..\variables\.npmrc" -Destination ".\"
      - name: Run Python script
        run: |
          cd C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\
          python check-sign.py
      - name: Check file
        run: |
          cd "C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\pc-cloud"
          ls release/build/
